# Generated by Django 4.2 on 2023-04-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_delivery.dish')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.employee')),
            ],
        ),
    ]
