# Generated by Django 4.2 on 2023-04-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.dish')),
            ],
        ),
    ]
