# Generated by Django 4.2 on 2023-04-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0003_alter_dish_price_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.dish'),
        ),
    ]
