# Generated by Django 4.2 on 2023-04-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0004_alter_food_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
