# Generated by Django 4.2 on 2023-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0005_delete_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='dish',
        ),
        migrations.AddField(
            model_name='food',
            name='dish',
            field=models.ManyToManyField(to='food_delivery.dish'),
        ),
    ]
