# Generated by Django 4.2 on 2023-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0006_remove_food_dish_food_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ManyToManyField(to='food_delivery.dish'),
        ),
    ]
