# Generated by Django 4.2 on 2023-04-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0007_remove_orderitem_dish_orderitem_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.dish'),
            preserve_default=False,
        ),
    ]
