# Generated by Django 4.2 on 2023-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0008_remove_orderitem_dish_orderitem_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ManyToManyField(to='food_delivery.dish'),
        ),
    ]
