# Generated by Django 4.2 on 2023-04-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0010_remove_orderitem_dish_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
