# Generated by Django 4.2 on 2023-05-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0017_alter_order_options_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
    ]
